# Generated by Django 5.2.7 on 2025-12-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('mru_to_tl', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_mru', models.PositiveIntegerField()),
                ('amount_tl', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_mru', models.PositiveIntegerField()),
                ('amount_tl', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('certain', 'Certain (Green)'), ('probable', 'Probable (Yellow)'), ('uncertain', 'Uncertain (Red)')], default='certain', max_length=50)),
                ('i_owe', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_mru', models.PositiveIntegerField()),
                ('amount_tl', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('certain', 'Certain (Green)'), ('probable', 'Probable (Yellow)'), ('uncertain', 'Uncertain (Red)')], default='certain', max_length=50)),
                ('owe_me', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='finance.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_mru', models.PositiveIntegerField()),
                ('amount_tl', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('i_owe', models.BooleanField(default=False)),
                ('owe_me', models.BooleanField(default=False)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='finance.cycle')),
            ],
        ),
    ]
