# Generated by Django 5.2.7 on 2025-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount_mru',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount_tl',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
