# Generated by Django 5.2.17 on 2026-10-03 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cycle",
            options={"ordering": ["-start", "-pk"]},
        ),
        migrations.AddField(
            model_name="cycle",
            name="end",
            field=models.DateField(null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="currency_symbol",
            field=models.CharField(
                default="TL", max_length=10, verbose_name="Currency"
            ),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="start",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="cycle",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="purpose",
            field=models.CharField(max_length=100, verbose_name="Purpose"),
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(verbose_name="Current balance")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="finance.cycle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("target", models.PositiveIntegerField(verbose_name="Target")),
                (
                    "monthly_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Amount per cycle"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Deadline"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        default="expense",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "amount",
                    models.PositiveIntegerField(default=0, verbose_name="Amount"),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("certain", "Certain"),
                            ("probable", "Probable"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="certain",
                        max_length=10,
                        verbose_name="How sure is it?",
                    ),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="Done")),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("is_debt", models.BooleanField(default=False, verbose_name="Debt")),
                ("previous_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="finance.cycle",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="finance.savingsgoal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ["-amount", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SavingsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savings_transaction",
                        to="finance.entry",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.savingsgoal",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
