# Generated by Django 5.2.7 on 2025-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_income_amount_mru_alter_income_amount_tl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount_mru',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount_tl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
