# Generated by Django 5.2.17 on 2026-10-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_copy_old_transactions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="cycle",
        ),
        migrations.RemoveField(
            model_name="special",
            name="cycle",
        ),
        migrations.AlterField(
            model_name="cycle",
            name="end",
            field=models.DateField(verbose_name="End date"),
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Income",
        ),
        migrations.DeleteModel(
            name="Special",
        ),
    ]
