# Generated by Django 5.2.7 on 2025-12-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_income_amount_mru_alter_income_amount_tl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount_mru',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount_tl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='finance.cycle'),
        ),
        migrations.AlterField(
            model_name='income',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='finance.cycle'),
        ),
        migrations.AlterField(
            model_name='special',
            name='amount_mru',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='amount_tl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='finance.cycle'),
        ),
    ]
