# Generated by Django 5.2.17 on 2026-10-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_remove_old_transactions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckIn",
        ),
    ]
