# Generated by Django 5.2.7 on 2025-12-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_amount_mru_alter_expense_amount_tl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
    ]
