# Generated by Django 5.2.7 on 2025-12-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_expense_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringexpense',
            old_name='title',
            new_name='purpose',
        ),
    ]
