# Generated by Django 5.2.7 on 2025-12-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_title_recurringexpense_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount_mru',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount_tl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
