# Generated by Django 5.2.7 on 2025-12-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_recurringexpense_amount_mru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
